{
 "title": "AsyncAPI Analytics: Client Statistics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(amax_application_info, organization)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\"}, application)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(amax_environment_info{organization=\"$organization\"}, environment)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(amax_client_uptime_seconds_total{organization=\"$organization\",environment=\"$environment\",application=\"$application\"}, client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}) by (client_id)",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[1m:1m]) * 60)[$__range:1m])) by (client_id)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_received_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[1m:1m]) * 60)[$__range:1m])) by (client_id)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Messages Discarded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[1m:1m]) * 60)[$__range:1m])) by (client_id)",
     "legendFormat": "Discarded"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_sent_bytes_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[1m:1m]) * 60)[$__range:1m])) by (client_id)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_received_bytes_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[1m:1m]) * 60)[$__range:1m])) by (client_id)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Last Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(timestamp(sum(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environment\",client_id=\"$client\"\n}) by(client_id))[1y:$__interval]) * 1000",
     "legendFormat": "Last Active"
    }
   ]
  },
  {
   "title": "Message Rate (msg/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(amax_client_messages_received_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Data Rate (byte/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(amax_client_messages_sent_bytes_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(amax_client_messages_received_bytes_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Message Discards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  environment=\"$environment\",client_id=\"$client\",type=\"incoming\",reason=\"noSubscriptionMatch\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "No Subscription Match"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\",type=\"incoming\",reason=\"topicParseError\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Topic Parse Error"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\",type=\"incoming\",reason=\"webParseError\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",application=\"$application\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Parse Error (Web)"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\",type=\"incoming\",reason=\"publishTopicAcl\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Publish Topic ACL"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\",type=\"incoming\",reason=\"msgSpoolCongestion\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Message Spool Congestion"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\",type=\"incoming\",reason=\"msgSpoolDiscards\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Message Spool Discards"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\",type=\"outgoing\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_received_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"} * 0) by (organization, application)",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "count(sum_over_time(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=\"$environment\",client_id=\"$client\"\n}[$__interval:1m])) by (client_id)\nor label_replace(vector(0),\"client_id\",\"$client\",\"\",\".*\")",
     "legendFormat": " "
    }
   ]
  }
 ]
}