{
 "title": "AsyncAPI Analytics: Team & Developer Statistics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(amax_application_info, organization)"
    }
   },
   { "name": "type", "label": "Team or Developer", "query": "team, developer" },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\",type=~\"$type\"}, owner)"
    }
   },
   {
    "name": "applications",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}, application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  max(max_over_time(\n    amax_client_uptime_seconds_total{organization=\"$organization\",application=~\"$applications\"}[$__range:1m]\n  )) by (application)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Inactive Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  max_over_time(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}[1y:$__interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  max(max_over_time(\n    amax_client_uptime_seconds_total{organization=\"$organization\",application=~\"$applications\"}[$__range:1m]\n  )) by (application)\n)\nor vector(0)"
    }
   ]
  },
  {
   "title": "Top 3 Applications by Messages Sent",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,\n  sum(sum_over_time((rate(\n    amax_client_messages_sent_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n  ) * 60)[$__range:1m])) by (application)\n)"
    }
   ]
  },
  {
   "title": "Top 3 Applications by Messages Received",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,\n  sum(sum_over_time((rate(\n    amax_client_messages_received_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n  ) * 60)[$__range:1m])) by (application)\n)"
    }
   ]
  },
  {
   "title": "Application Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(max_over_time(\n  amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}[$__range:1m]\n)) by (application)"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_sent_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n) * 60)[$__range:1m])) by (application)\nor vector(0)"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_received_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n) * 60)[$__range:1m])) by (application)\nor vector(0)"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_discarded_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n) * 60)[$__range:1m])) by (application)\nor vector(0)"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_sent_bytes_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n) * 60)[$__range:1m])) by (application)\nor vector(0)"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_received_bytes_total{organization=\"$organization\",application=~\"$applications\"}[1m:1m]\n) * 60)[$__range:1m])) by (application)\nor vector(0)"
    },
    {
     "expr": "present_over_time((count(\n    amax_client_uptime_seconds_total{organization=\"$organization\",application=~\"$applications\"}\n) by (application))[$__range:1m])\nor vector(0)"
    }
   ]
  }
 ]
}