{
 "title": "AsyncAPI Analytics: Application Statistics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(amax_application_info, organization)"
    }
   },
   { "name": "type", "label": "Team or Developer", "query": "team, developer" },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\",type=\"$type\"}, owner)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\",type=\"$type\",owner=\"$owner\"}, application)"
    }
   },
   {
    "name": "environments",
    "label": "Environments",
    "query": {
     "query": "label_values(amax_environment_info{organization=\"$organization\"}, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(amax_client_uptime_seconds_total{organization=\"$organization\",environment=~\"$environments\",application=\"$application\"}) by (application)"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (application)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_received_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (application)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Messages Discarded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (application)",
     "legendFormat": "Discarded"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_sent_bytes_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (application)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(amax_client_messages_received_bytes_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (application)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Last Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(timestamp(sum(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}) by(application))[1y:$__interval]) * 1000",
     "legendFormat": "Last Active"
    }
   ]
  },
  {
   "title": "Message Rate (msg/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(amax_client_messages_received_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Data Rate (byte/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(amax_client_messages_sent_bytes_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(amax_client_messages_received_bytes_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Message Discards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"noSubscriptionMatch\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "No Subscription Match"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"topicParseError\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Topic Parse Error"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"webParseError\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Parse Error (Web)"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"publishTopicAcl\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Publish Topic ACL"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"msgSpoolCongestion\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Message Spool Congestion"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"incoming\",reason=\"msgSpoolDiscards\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_sent_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Message Spool Discards"
    },
    {
     "expr": "(sum(rate(amax_client_messages_discarded_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\",type=\"outgoing\"\n}[$__interval:1m])) by (organization, application) /\nsum(rate(amax_client_messages_received_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__interval:1m])) by (organization, application) > 0)\nor sum(amax_application_info{organization=\"$organization\",application=\"$application\"}) by (organization,application) * 0",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(\n  clamp_max(amax_client_uptime_seconds_total{organization=\"$organization\",environment=~\"$environments\",application=\"$application\"}, 1)\n) by (application)\nor sum(amax_application_info{organization=\"$organization\",type=\"team\",owner=\"$owner\",application=\"$application\"} * 0) by (application)",
     "legendFormat": "Client Connections"
    }
   ]
  },
  {
   "title": "Details for Clients, WebHooks, and Guaranteed Messaging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum_over_time((rate(amax_client_messages_sent_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "sum_over_time((rate(amax_client_messages_received_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "sum_over_time(sum(rate(amax_client_messages_discarded_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60) without(type, reason) [$__range:1m])"
    },
    {
     "expr": "sum_over_time((rate(amax_client_messages_sent_bytes_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "sum_over_time((rate(amax_client_messages_received_bytes_total{\n    organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "clamp_max(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}, 1) or\nmax_over_time(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__range:1m]) * 0"
    },
    {
     "expr": "amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n} or\nmax_over_time(amax_client_uptime_seconds_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[$__range:1m]) * 0"
    }
   ]
  },
  {
   "title": "WebHooks",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum_over_time((rate(amax_rdp_http_requests_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "sum_over_time((rate(amax_rdp_http_requests_bytes_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "(sum_over_time((rate(amax_rdp_http_responses_error_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m]) + \nsum_over_time((rate(amax_rdp_http_responses_timeout_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) / \nsum_over_time((rate(amax_rdp_http_responses_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])"
    },
    {
     "expr": "sum(amax_rdp_up{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}) by (environment, rdp_name)"
    }
   ]
  },
  {
   "title": "Guaranteed Messaging",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "label_replace(sum(amax_queue_consumer_count{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}) by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    },
    {
     "expr": "label_replace(sum(amax_queue_messages_queued{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}) by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    },
    {
     "expr": "label_replace(sum(amax_queue_message_spool_usage_bytes{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}) by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    },
    {
     "expr": "label_replace(sum(amax_queue_message_spool_peak_usage_bytes{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n})by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    },
    {
     "expr": "label_replace(sum(sum_over_time((rate(amax_queue_messages_spooled_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    },
    {
     "expr": "label_replace(sum(sum_over_time((rate(amax_queue_messages_not_queued_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (environment, queue_name) +\nsum(sum_over_time((rate(amax_queue_messages_removed_total{\n  organization=\"$organization\",environment=~\"$environments\",application=\"$application\"\n}[1m:1m]) * 60)[$__range:1m])) by (environment, queue_name), \"queue_name\", \"$1\", \"queue_name\", \"[^-]+-(.*)\")"
    }
   ]
  }
 ]
}