{
 "title": "AsyncAPI Analytics: Team & Developer Statistics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(amax_application_info, organization)"
    }
   },
   { "name": "type", "label": "Team or Developer", "query": "team, developer" },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(amax_application_info{organization=\"$organization\",type=~\"$type\"}, owner)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 3: Producer Applications",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,\n  sum(sum_over_time((rate(\n    amax_client_messages_sent_total{organization=\"$organization\"}[1m:1m]\n  ) * 60)[$__range:1m])) by (application) * on(application) group_left(owner)\n  max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\n)"
    }
   ]
  },
  {
   "title": "Top 3: Consumer Applications",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,\n  sum(sum_over_time((rate(\n    amax_client_messages_received_total{organization=\"$organization\"}[1m:1m]\n  ) * 60)[$__range:1m])) by (application) * on(application) group_left(owner)\n  max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\n)"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_sent_total{organization=\"$organization\"}[1m:1m]\n) * 60)[$__range:1m])) by (application) * on(application) group_left()\nmax(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\nor max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application) * 0"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_received_total{organization=\"$organization\"}[1m:1m]\n) * 60)[$__range:1m])) by (application) * on(application) group_left()\nmax(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\nor max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application) * 0"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_discarded_total{organization=\"$organization\"}[1m:1m]\n) * 60)[$__range:1m])) by (application) * on(application) group_left()\nmax(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\nor max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application) * 0"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_sent_bytes_total{organization=\"$organization\"}[1m:1m]\n) * 60)[$__range:1m])) by (application) * on(application) group_left()\nmax(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\nor max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application) * 0"
    },
    {
     "expr": "sum(sum_over_time((rate(\n  amax_client_messages_received_bytes_total{organization=\"$organization\"}[1m:1m]\n) * 60)[$__range:1m])) by (application) * on(application) group_left()\nmax(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application)\nor max(amax_application_info{organization=\"$organization\",type=~\"$type\",owner=~\"$owner\"}) by (application) * 0"
    }
   ]
  }
 ]
}